"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 6.0.8.
"""

from pathlib import Path
from datetime import timedelta
import os
import sys
from dotenv import load_dotenv

BASE_DIR = Path(__file__).resolve().parent.parent

# A deployment-provided SECRET_KEY must always override local dotenv values.
_deployment_secret_key = os.environ.get("SECRET_KEY")
_deployment_allowed_hosts = os.environ.get("ALLOWED_HOSTS")
load_dotenv(BASE_DIR / ".env")


# SECURITY

SECRET_KEY = (
    _deployment_secret_key
    or os.getenv("DEPLOYMENT_SECRET_KEY")
    or os.getenv("SECRET_KEY", "")
)

DEBUG = os.getenv("DEBUG", "False").lower() in ("true", "1", "t")
_IS_TESTING = "test" in sys.argv

_allowed_hosts_value = (
    _deployment_allowed_hosts
    or os.getenv("DEPLOYMENT_ALLOWED_HOSTS")
    or os.getenv("ALLOWED_HOSTS", "")
)
ALLOWED_HOSTS = [host.strip() for host in _allowed_hosts_value.split(",") if host.strip()]
if not DEBUG:
    if (
        len(SECRET_KEY) < 50
        or len(set(SECRET_KEY)) < 5
        or SECRET_KEY.startswith("django-insecure-")
    ):
        raise RuntimeError(
            "A strong SECRET_KEY must be configured through the environment when DEBUG=False"
        )
    if not ALLOWED_HOSTS or "*" in ALLOWED_HOSTS:
        raise RuntimeError(
            "ALLOWED_HOSTS must contain explicit production hosts when DEBUG=False"
        )


# Application definition

INSTALLED_APPS = [
    "nested_admin",
    "jazzmin",

    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "myapp.apps.MyappConfig",
    "payment",

    "rest_framework",
    "rest_framework_simplejwt.token_blacklist",
    "corsheaders",
]


MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",

    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "myapp.middleware.AbuseProtectionMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


ROOT_URLCONF = "myproject.urls"


TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


WSGI_APPLICATION = "myproject.wsgi.application"


# DATABASE

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": os.getenv("DB_NAME"),
        "USER": os.getenv("DB_USER"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": os.getenv("DB_HOST","127.0.0.1"),
        "PORT": os.getenv("DB_PORT","3306"),
    }
}


# Password validation

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "myapp.password_policy.StrongPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files

STATIC_URL = "static/"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STATIC_ROOT = BASE_DIR / "staticfiles"


# Media

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "uploads"


# User Model

AUTH_USER_MODEL = "myapp.User"


# REST Framework

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "myapp.authentication.CookieJWTAuthentication",
    ),
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "DEFAULT_THROTTLE_CLASSES": (
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ),
    "DEFAULT_THROTTLE_RATES": {
        "anon": os.getenv("API_ANON_RATE", "120/min"),
        "user": os.getenv("API_USER_RATE", "600/min"),
        "auth": os.getenv("AUTH_RATE", "10/min"),
        "payment": os.getenv("PAYMENT_RATE", "10/min"),
        "search": os.getenv("SEARCH_RATE", "60/min"),
    },
    "PAGE_SIZE": 50,
}


# JWT

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": False,
    "ALGORITHM": "HS256",
    "AUTH_HEADER_TYPES": ("Bearer",),
}

# Browser JWTs stay in HttpOnly cookies.  `None` is only appropriate where
# the storefront and API are genuinely cross-site; it requires strict CORS and
# CSRF configuration below.  Lax is the safer default for same-site subdomains.
JWT_ACCESS_COOKIE_NAME = "eehook_access"
JWT_REFRESH_COOKIE_NAME = "eehook_refresh"
JWT_COOKIE_DOMAIN = os.getenv("JWT_COOKIE_DOMAIN", "").strip()
JWT_COOKIE_SAMESITE = os.getenv("JWT_COOKIE_SAMESITE", "Lax").strip().title()
if JWT_COOKIE_SAMESITE not in {"Lax", "Strict", "None"}:
    raise RuntimeError("JWT_COOKIE_SAMESITE must be Lax, Strict, or None")
JWT_COOKIE_SECURE = not DEBUG


# Google Login

GOOGLE_CLIENT_ID = os.getenv("GOOGLE_CLIENT_ID")


# Email

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True

EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")


# CORS: browser cookies require an explicit, trusted storefront allowlist.
# Never enable a wildcard origin together with credentials.
_storefront_origins = os.getenv("STOREFRONT_ORIGINS", os.getenv("CORS_ALLOWED_ORIGINS", ""))
CORS_ALLOWED_ORIGINS = [origin.strip().rstrip("/") for origin in _storefront_origins.split(",") if origin.strip()]
# Local Vite development uses HTTP localhost origins. Keep these confined to
# DEBUG builds; production remains an explicit HTTPS storefront allowlist.
if DEBUG:
    for _local_origin in ("http://localhost:5173", "http://127.0.0.1:5173"):
        if _local_origin not in CORS_ALLOWED_ORIGINS:
            CORS_ALLOWED_ORIGINS.append(_local_origin)
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOW_CREDENTIALS = True
CSRF_TRUSTED_ORIGINS = CORS_ALLOWED_ORIGINS.copy()
if "*" in CORS_ALLOWED_ORIGINS:
    raise RuntimeError("STOREFRONT_ORIGINS must not contain a wildcard origin")
if not (DEBUG or _IS_TESTING) and not CORS_ALLOWED_ORIGINS:
    raise RuntimeError("STOREFRONT_ORIGINS must contain explicit HTTPS origins when DEBUG=False")
if not (DEBUG or _IS_TESTING) and any(not origin.startswith("https://") for origin in CORS_ALLOWED_ORIGINS):
    raise RuntimeError("STOREFRONT_ORIGINS must use HTTPS when DEBUG=False")

# Conservative production defaults. Override only with an explicit deployment
# configuration (for example TLS termination at a reverse proxy).
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = "same-origin"
X_FRAME_OPTIONS = "DENY"
SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin"
SECURE_SSL_REDIRECT = not (DEBUG or _IS_TESTING)
# The reverse proxy/load balancer must overwrite X-Forwarded-Proto, not pass a
# client supplied value through.  This lets Django recognise HTTPS termination.
if not DEBUG and os.getenv("TRUST_PROXY_SSL_HEADER", "true").lower() in ("true", "1", "t"):
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SESSION_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SECURE = not DEBUG
# JavaScript must be able to read this non-secret token and return it in the
# X-CSRFToken header. Authentication JWTs remain HttpOnly.
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SAMESITE = JWT_COOKIE_SAMESITE
SECURE_HSTS_SECONDS = int(os.getenv("SECURE_HSTS_SECONDS", "31536000" if not DEBUG else "0"))
SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG
SECURE_HSTS_PRELOAD = not DEBUG

# Reject oversized request bodies before application code parses them.
DATA_UPLOAD_MAX_MEMORY_SIZE = int(os.getenv("DATA_UPLOAD_MAX_MEMORY_SIZE", str(10 * 1024 * 1024)))
FILE_UPLOAD_MAX_MEMORY_SIZE = int(os.getenv("FILE_UPLOAD_MAX_MEMORY_SIZE", str(5 * 1024 * 1024)))

# Throttling, token blacklisting, and abuse protections must use a shared
# cache in production. LocMemCache is safe only for a single local process.
if DEBUG or _IS_TESTING:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "backend-development-cache",
        }
    }
else:
    MEMCACHED_LOCATION = os.getenv("MEMCACHED_LOCATION", "").strip()
    if not MEMCACHED_LOCATION:
        raise RuntimeError(
            "MEMCACHED_LOCATION must be configured when DEBUG=False "
            "(for example, 127.0.0.1:11211)."
        )
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.memcached.PyMemcacheCache",
            "LOCATION": MEMCACHED_LOCATION,
            "OPTIONS": {
                "no_delay": True,
                "use_pooling": True,
                "ignore_exc": False,
            },
        }
    }
GLOBAL_RATE_LIMIT = int(os.getenv("GLOBAL_RATE_LIMIT", "300"))
GLOBAL_RATE_WINDOW = int(os.getenv("GLOBAL_RATE_WINDOW", "60"))
ADMIN_LOGIN_MAX_ATTEMPTS = int(os.getenv("ADMIN_LOGIN_MAX_ATTEMPTS", "5"))
ADMIN_LOGIN_WINDOW = int(os.getenv("ADMIN_LOGIN_WINDOW", "900"))


# Frontend URL

SITE_URL = os.getenv("SITE_URL", "http://localhost:5173").rstrip("/")
if not (DEBUG or _IS_TESTING) and not SITE_URL.startswith("https://"):
    raise RuntimeError("SITE_URL must use HTTPS when DEBUG=False")


# Stripe

STRIPE_PUBLISHABLE_KEY = os.getenv("STRIPE_PUBLISHABLE_KEY")
STRIPE_SECRET_KEY = os.getenv("STRIPE_SECRET_KEY")
STRIPE_WEBHOOK_SECRET = os.getenv("STRIPE_WEBHOOK_SECRET")

# WhatsApp Cloud API. The owner number is stored as digits only, including
# country code (971547369369), as required by Meta's API.
WHATSAPP_ACCESS_TOKEN = os.getenv("WHATSAPP_ACCESS_TOKEN", "")
WHATSAPP_PHONE_NUMBER_ID = os.getenv("WHATSAPP_PHONE_NUMBER_ID", "")
WHATSAPP_OWNER_PHONE = os.getenv("WHATSAPP_OWNER_PHONE", "971547369369")
WHATSAPP_API_VERSION = os.getenv("WHATSAPP_API_VERSION", "v22.0")


# Default primary key

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
