# Generated by Django 6.0.7 on 2026-09-27 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product', 'color')},
        ),
        migrations.AddField(
            model_name='productvariant',
            name='regions',
            field=models.ManyToManyField(blank=True, to='myapp.region'),
        ),
        migrations.AlterField(
            model_name='productvariantunit',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='myapp.productvariant'),
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='region',
        ),
    ]
