# Generated by Django 6.0.7 on 2026-09-27 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_productvariant_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSideBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='The actual image file', upload_to='hero_side_banners/')),
                ('link', models.URLField(blank=True, help_text='A URL where the user should be redirected if they click the banner', max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Only one banner should be active at a time')),
            ],
        ),
        migrations.CreateModel(
            name='PromoBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='The promotional message (e.g., "VISA - Extra 15% off with Visa Credit Cards")', max_length=255)),
                ('bg_color', models.CharField(default='#1A3B8B', help_text='Hex code for the background color', max_length=50)),
                ('text_color', models.CharField(default='#FFFFFF', help_text='Hex code for the text color', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='To easily turn individual banners on or off')),
            ],
        ),
    ]
