# Generated by Django 6.0.7 on 2026-07-25 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_order_payment_method_order_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='variant_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.productvariantsize'),
        ),
    ]
