# Generated by Django 6.0.7 on 2026-09-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_herosidebanner_promobanner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promobanner',
            name='bg_color',
        ),
        migrations.RemoveField(
            model_name='promobanner',
            name='text',
        ),
        migrations.RemoveField(
            model_name='promobanner',
            name='text_color',
        ),
        migrations.AddField(
            model_name='promobanner',
            name='image',
            field=models.ImageField(blank=True, help_text='The promotional banner image', null=True, upload_to='promo_banners/'),
        ),
        migrations.AddField(
            model_name='promobanner',
            name='link',
            field=models.URLField(blank=True, help_text='A URL where the user should be redirected if they click the banner', max_length=500, null=True),
        ),
    ]
