# Generated by Django 6.0.7 on 2026-09-29 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_promobanner_bg_color_remove_promobanner_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='multiple_price_heading',
            field=models.CharField(blank=True, help_text='e.g. GB, Liter', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='For single price', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='price_type',
            field=models.CharField(choices=[('single', 'Single Price'), ('multiple', 'Multiple Price')], default='single', max_length=20),
        ),
        migrations.AddField(
            model_name='productvariantunit',
            name='quantity_string',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Quantity/Subheading (e.g. 128, 1kg)'),
        ),
    ]
