# Generated by Django 6.0.7 on 2026-09-29 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_productvariant_multiple_price_heading_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='multiple_price_heading',
        ),
        migrations.RemoveField(
            model_name='productvariantunit',
            name='quantity_string',
        ),
        migrations.AddField(
            model_name='productvariantunit',
            name='unit_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.unittype', verbose_name='Unit (e.g. GB/KG)'),
        ),
        migrations.AlterField(
            model_name='productvariantunit',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.unit', verbose_name='Quantity (e.g. 128, 1)'),
        ),
    ]
