# Generated by Django 6.0.7 on 2026-09-29 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_productvariant_multiple_price_heading_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='cart',
            name='variant_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.productvariantunit'),
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('user', 'variant', 'variant_unit')},
        ),
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('user', 'variant', 'variant_unit')},
        ),
    ]
