# Generated by Django 6.0.7 on 2026-09-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_cart_unique_together_alter_cart_variant_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='promotional_banner_url',
        ),
        migrations.AddField(
            model_name='product',
            name='promotional_banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='promotional_banners/'),
        ),
    ]
