# Generated by Django 6.0.7 on 2026-09-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_coupon_couponusage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(blank=True, help_text='Leave blank to auto-generate', max_length=50, unique=True),
        ),
    ]
