# Generated by Django 6.0.7 on 2026-09-29 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_coupon_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='couponusage',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='product',
        ),
        migrations.AddField(
            model_name='coupon',
            name='products',
            field=models.ManyToManyField(blank=True, help_text='Select specific products. Leave blank to apply to ALL products.', related_name='coupons', to='myapp.product'),
        ),
        migrations.AddField(
            model_name='couponusage',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usages', to='myapp.product'),
        ),
        migrations.AlterUniqueTogether(
            name='couponusage',
            unique_together={('coupon', 'user', 'product')},
        ),
    ]
