# Generated by Django 6.0.7 on 2026-09-30 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_cart_coupon_savedcoupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='quantity',
            field=models.PositiveIntegerField(default=0, help_text='For single price'),
        ),
    ]
