# Generated by Django 6.0.7 on 2026-09-30 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_productvariant_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariant',
            old_name='quantity',
            new_name='stock',
        ),
    ]
