# Generated by Django 6.0.7 on 2026-10-01 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_wishlist_cancelled_at_wishlist_cancelled_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={},
        ),
        migrations.RemoveField(
            model_name='unit',
            name='order',
        ),
    ]
