# Generated by Django 6.0.7 on 2026-10-02 15:25

import django.db.models.deletion
from django.db import migrations, models


def backfill_image_positions(apps, schema_editor):
    ProductImage = apps.get_model("myapp", "ProductImage")
    variant_ids = (
        ProductImage.objects.order_by().values_list("variant_id", flat=True).distinct()
    )
    for variant_id in variant_ids:
        images = ProductImage.objects.filter(variant_id=variant_id).order_by("id")
        for position, image in enumerate(images):
            ProductImage.objects.filter(pk=image.pk).update(position=position)


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_unit_options_remove_unit_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ('position', 'id')},
        ),
        migrations.AddField(
            model_name='productimage',
            name='position',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='sku',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='productvariantunit',
            name='sku',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.RunPython(backfill_image_positions, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='productimage',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='myapp.productvariant'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(fields=('unit_type', 'name'), name='myapp_unit_type_name_unique'),
        ),
    ]
