# Generated by Django 6.0.7 on 2026-10-04 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_seed_unit_catalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='emi_available',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='emi_starting_price',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True),
        ),
    ]
