# Generated by Django 6.0.7 on 2026-10-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0022_brand_product_brand"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrustBenefit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.SlugField(max_length=100, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "icon_key",
                    models.CharField(
                        choices=[
                            ("secure-payment", "Secure payment"),
                            ("delivery-information", "Delivery information"),
                            ("customer-support", "Customer support"),
                            ("easy-returns", "Easy returns"),
                        ],
                        max_length=32,
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ("display_order", "id")},
        ),
    ]
