# Generated by Django 6.0.7 on 2026-10-08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0022_coupon_applicability_type_coupon_category_and_more"),
        ("myapp", "0023_trustbenefit"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="related_product_mode",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("manual", "Manual"),
                    ("automatic", "Automatic"),
                ],
                default="none",
                help_text="Choose whether related products are hidden, curated manually, or selected automatically.",
                max_length=12,
            ),
        ),
        migrations.CreateModel(
            name="ProductRelatedProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.PositiveSmallIntegerField(
                        help_text="Display order, from 0 to 3.",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(3),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_product_links",
                        to="myapp.product",
                    ),
                ),
                (
                    "related_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_from_links",
                        to="myapp.product",
                    ),
                ),
            ],
            options={"ordering": ("position", "id")},
        ),
        migrations.AddField(
            model_name="product",
            name="related_products",
            field=models.ManyToManyField(
                blank=True,
                related_name="related_to_products",
                through="myapp.ProductRelatedProduct",
                to="myapp.product",
            ),
        ),
        migrations.AddConstraint(
            model_name="productrelatedproduct",
            constraint=models.UniqueConstraint(
                fields=("product", "related_product"),
                name="myapp_related_product_unique_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="productrelatedproduct",
            constraint=models.UniqueConstraint(
                fields=("product", "position"),
                name="myapp_related_product_unique_position",
            ),
        ),
        migrations.AddConstraint(
            model_name="productrelatedproduct",
            constraint=models.CheckConstraint(
                condition=models.Q(("position__gte", 0), ("position__lte", 3)),
                name="myapp_related_product_position_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="productrelatedproduct",
            constraint=models.CheckConstraint(
                condition=~models.Q(("product", models.F("related_product"))),
                name="myapp_related_product_not_self",
            ),
        ),
    ]
