# Generated by Django 6.0.7 on 2026-10-08 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_related_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='WelcomeBonusNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='WelcomeBonusRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion_type', models.CharField(default='WELCOME_BONUS', editable=False, max_length=32)),
                ('redemption_code', models.CharField(editable=False, max_length=64)),
                ('discount_type', models.CharField(max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('applied_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WelcomeBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('applicability_type', models.CharField(choices=[('PRODUCT', 'Product'), ('CATEGORY', 'Category')], default='PRODUCT', max_length=20)),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FIXED', 'Fixed Amount')], default='PERCENTAGE', max_length=20)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fixed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='welcome_bonuses', to='myapp.category')),
                ('products', models.ManyToManyField(blank=True, help_text='Select the eligible products for a product-wise campaign.', related_name='welcome_bonuses', to='myapp.product')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='WelcomeBonusAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('CLAIMED', 'Claimed'), ('REDEEMED', 'Redeemed')], default='AVAILABLE', max_length=12)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='welcome_bonus_assignments', to=settings.AUTH_USER_MODEL)),
                ('welcome_bonus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='myapp.welcomebonus')),
            ],
        ),
        migrations.CreateModel(
            name='WelcomeBonusApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='welcome_bonus_applications', to='myapp.product')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='myapp.welcomebonusassignment')),
            ],
        ),
        migrations.CreateModel(
            name='SavedWelcomeBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_welcome_bonuses', to='myapp.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_welcome_bonuses', to=settings.AUTH_USER_MODEL)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_products', to='myapp.welcomebonusassignment')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='welcome_bonus_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to='myapp.welcomebonusassignment'),
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.CheckConstraint(condition=models.Q(('coupon__isnull', True), ('welcome_bonus_assignment__isnull', True), _connector='OR'), name='myapp_cart_one_promotion_source'),
        ),
        migrations.AddField(
            model_name='welcomebonusnotification',
            name='assignment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='myapp.welcomebonusassignment'),
        ),
        migrations.AddField(
            model_name='welcomebonusredemption',
            name='assignment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='redemption', to='myapp.welcomebonusassignment'),
        ),
        migrations.AddField(
            model_name='welcomebonusredemption',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='welcome_bonus_redemptions', to='myapp.order'),
        ),
        migrations.AddField(
            model_name='welcomebonusredemption',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='welcome_bonus_redemptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='welcomebonusredemption',
            name='welcome_bonus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='myapp.welcomebonus'),
        ),
        migrations.AddConstraint(
            model_name='welcomebonus',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='myapp_welcome_bonus_valid_dates'),
        ),
        migrations.AddConstraint(
            model_name='welcomebonus',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('discount_percentage__gt', 0), ('discount_percentage__lte', 100), ('discount_type', 'PERCENTAGE'), ('fixed_amount__isnull', True)), models.Q(('discount_percentage__isnull', True), ('discount_type', 'FIXED'), ('fixed_amount__gt', 0)), _connector='OR'), name='myapp_welcome_bonus_valid_discount'),
        ),
        migrations.AddIndex(
            model_name='welcomebonusassignment',
            index=models.Index(fields=['user', 'status'], name='myapp_welco_user_id_019f82_idx'),
        ),
        migrations.AddConstraint(
            model_name='welcomebonusassignment',
            constraint=models.UniqueConstraint(fields=('welcome_bonus', 'user'), name='myapp_welcome_bonus_one_assignment_per_user'),
        ),
        migrations.AddConstraint(
            model_name='welcomebonusapplication',
            constraint=models.UniqueConstraint(fields=('assignment', 'product'), name='myapp_welcome_bonus_one_application_per_product'),
        ),
        migrations.AddConstraint(
            model_name='savedwelcomebonus',
            constraint=models.UniqueConstraint(fields=('user', 'product'), name='myapp_saved_welcome_bonus_per_product'),
        ),
        migrations.AddIndex(
            model_name='welcomebonusredemption',
            index=models.Index(fields=['order', 'promotion_type'], name='myapp_welco_order_i_68f32c_idx'),
        ),
    ]
