# Generated by Django 6.0.8 on 2026-10-08

from django.db import migrations, models


def normalize_blank_stripe_session_ids(apps, schema_editor):
    Order = apps.get_model("myapp", "Order")
    Order.objects.filter(stripe_session_id="").update(stripe_session_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0025_welcomebonusnotification_welcomebonusredemption_and_more"),
    ]

    operations = [
        migrations.RunPython(normalize_blank_stripe_session_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="order",
            name="stripe_session_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
